DROP TABLE IF EXISTS "GROUPS";
DROP TABLE IF EXISTS "MESSAGES";
DROP TABLE IF EXISTS "USERS";


CREATE TABLE "GROUPS" (
	"GroupId"	INTEGER,
	"UserId"	INTEGER,
	PRIMARY KEY("UserId","GroupId"),
    FOREIGN KEY("GroupId") REFERENCES USERS("Id"),
    FOREIGN KEY("UserId") REFERENCES USERS("Id")
);
CREATE TABLE "MESSAGES" (
	"SenderId"	INTEGER NOT NULL,
	"DestinationId"	INTEGER NOT NULL,
	"Message"	TEXT NOT NULL,
    "Date" TEXT NOT NULL,
    FOREIGN KEY("SenderId") REFERENCES USERS("Id"),
    FOREIGN KEY("DestinationId") REFERENCES USERS("Id")
);
CREATE TABLE "USERS" (
	"Id"	INTEGER NOT NULL,
	"Nickname"	TEXT NOT NULL,
	"Password"	INTEGER NOT NULL,
	PRIMARY KEY("Id")
);